spring:
  application:
    name: StockCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lab10
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
queue:
  name:
    input:  createDeleteQueue
    output: productStockQueue
